import { Separator } from "@/components/ui/separator";
import { SidebarProvider, SidebarTrigger } from "@/components/ui/sidebar";
import { RpcProvider } from "@/src/api/tools/RpcProvider";
import {
  ClerkProvider,
  RedirectToSignIn,
  SignedIn,
  SignedOut,
} from "@clerk/nextjs";
import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import { AppSidebar } from "./_components/app-sidebar";
import User from "./_components/user";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ClerkProvider>
      <html lang="en">
        <body
          className={`${geistSans.variable} ${geistMono.variable} antialiased`}
        >
          <RpcProvider>
            {/* login */}
            {/* <div className="flex flex-col gap-4 min-h-svh w-full items-center justify-center p-6 md:p-10">
          <h1>JumpHeroez</h1>
          <h2>Admin Portal</h2>
          <div className="w-full max-w-sm">
            <LoginForm />
          </div>
        </div> */}
            <SignedOut>
              <RedirectToSignIn />
            </SignedOut>
            {/* app */}
            <SignedIn>
              <SidebarProvider>
                <AppSidebar />
                <div className="flex flex-1 flex-col">
                  <header className="flex justify-between items-center h-16 border-b px-4">
                    <div className="flex items-center gap-2">
                      <SidebarTrigger className="-ml-1" />
                      <Separator
                        orientation="vertical"
                        className="mr-2 data-[orientation=vertical]:h-4"
                      />
                      <p>Adventure Park Mangagment</p>
                    </div>

                    <User />
                  </header>
                  <main className="p-4">{children}</main>
                </div>
              </SidebarProvider>
            </SignedIn>
          </RpcProvider>
        </body>
      </html>
    </ClerkProvider>
  );
}
